import { createClient } from '@supabase/supabase-js'
export const supabase = createClient('https://ieccqbynawpidfygitsq.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllY2NxYnluYXdwaWRmeWdpdHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4NTU5NjgsImV4cCI6MjA5NjQzMTk2OH0.3Mgx9cqrRC9rDuA0DJXSwyismgKVPkquvJK93bT5AJo')
